import { useState } from 'react'

const DOC_SECTIONS = [
  { key: 'problem',   label: 'Problem' },
  { key: 'affected',  label: 'Who is affected' },
  { key: 'mustHaves', label: 'Must-haves' },
  { key: 'noGoes',    label: 'No-goes' },
  { key: 'whatGood',  label: 'What good looks like' },
]

function renderContent(content) {
  if (!content) return null
  const lines = content.split('\n')
  const bullets = lines.filter(l => l.startsWith('- ')).map(l => l.slice(2))
  if (bullets.length > 0) {
    return <ul>{bullets.map((b, i) => <li key={i}>{b}</li>)}</ul>
  }
  return <p>{content}</p>
}

export default function DocPanel({ sections = {}, isLoading = false }) {
  const [copied, setCopied] = useState(false)

  const filledKeys = DOC_SECTIONS.filter(s => sections[s.key])
  const firstEmptyIdx = DOC_SECTIONS.findIndex(s => !sections[s.key])
  const isComplete = filledKeys.length === DOC_SECTIONS.length

  const copyAll = () => {
    const text = filledKeys.map(s => `${s.label}\n${sections[s.key]}`).join('\n\n')
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const exportPDF = () => {
    const filled = DOC_SECTIONS.filter(s => sections[s.key])
    const bodyHtml = filled.map(s => {
      const val = sections[s.key]
      const lines = val.split('\n')
      const bullets = lines.filter(l => l.startsWith('- ')).map(l => l.slice(2))
      const content = bullets.length > 0
        ? `<ul>${bullets.map(b => `<li>${b}</li>`).join('')}</ul>`
        : `<p>${val}</p>`
      return `<section><h2>${s.label}</h2>${content}</section>`
    }).join('')
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    const win = window.open('', '_blank')
    win.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>Phase 1 — Discovery Document</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500&family=DM+Mono:wght@400;500&display=swap');
  *{box-sizing:border-box;margin:0;padding:0;}
  body{font-family:'DM Sans',sans-serif;color:#1c1814;background:#fff;padding:60px 72px;max-width:760px;margin:0 auto;}
  header{margin-bottom:48px;padding-bottom:22px;border-bottom:2px solid #1c1814;display:flex;align-items:baseline;justify-content:space-between;}
  header h1{font-family:'DM Mono',monospace;font-size:12px;letter-spacing:0.14em;text-transform:uppercase;}
  header span{font-family:'DM Mono',monospace;font-size:10px;color:#857f78;}
  section{margin-bottom:36px;}
  h2{font-family:'DM Mono',monospace;font-size:9px;letter-spacing:0.14em;text-transform:uppercase;color:#c4620a;margin-bottom:10px;}
  p{font-size:14px;line-height:1.85;}
  ul{list-style:none;padding:0;display:flex;flex-direction:column;gap:6px;}
  li{font-size:14px;line-height:1.7;padding-left:16px;position:relative;}
  li::before{content:'—';position:absolute;left:0;color:#857f78;}
  footer{margin-top:56px;padding-top:18px;border-top:1px solid #ddd7cc;font-family:'DM Mono',monospace;font-size:10px;color:#857f78;}
</style>
</head><body>
<header><h1>◆ Discovery — Phase 1 Output</h1><span>${date}</span></header>
${bodyHtml}
<footer>Generated by Discovery · Phase 1: Understand the Problem</footer>
</body></html>`)
    win.document.close()
    win.onload = () => win.print()
  }

  return (
    <div className="doc-panel">
      <div className="doc-panel-header">
        <span className="doc-panel-title">Outcome</span>
        <span className="doc-panel-badge">Phase 1</span>
      </div>

      <div className="doc-panel-body">
        {DOC_SECTIONS.map((s, i) => {
          const val = sections[s.key]
          const isFilled  = !!val
          const isCurrent = !val && i === firstEmptyIdx
          const isPending = !val && i > firstEmptyIdx

          return (
            <div key={s.key} className={`doc-section${isFilled ? ' filled' : isCurrent ? ' current' : ' pending'}`}>
              <div className="doc-sec-label">
                {s.label}
                {isCurrent && isLoading && <div className="pulse-dot" />}
              </div>
              <div className="doc-sec-body">
                {isFilled
                  ? renderContent(val)
                  : isCurrent
                    ? <span className="doc-in-progress">In progress…</span>
                    : <span>—</span>
                }
              </div>
            </div>
          )
        })}
      </div>

      {filledKeys.length > 0 && (
        <div className="doc-panel-actions">
          <button className="doc-action-btn" onClick={copyAll}>
            {copied ? '✓ Copied' : isComplete ? 'Copy outcome' : 'Copy so far'}
          </button>
          <button className="doc-action-btn" onClick={exportPDF}>
            Export PDF
          </button>
        </div>
      )}
    </div>
  )
}
